const projectsData = [
    {
        name: 'Card Stack',
        tech: 'React • Styled Components',
        description: `I was searching around for a simple flashcard app, but most of the apps that I found required signing up and they just didn't have the look and feel that I wanted. So I made my own.`,
        src: 'CardStack_gttvbn',
        width: '700',
        height: '350',
        alt: 'Flashcards app',
        longDescription: {
            intro: `I was searching around for a simple flashcard app, but most of the apps that I found required signing up and they just didn't have the look and feel that I wanted. So I decided to make my own. I wanted something minimalistic without a bunch of features getting in the way of the simple process of flipping a card and then moving on to the next one.`,
            problems: `Initially, the card that was displayed was always the first card in an array. Moving from one card to the next was implemented by using the push and pop array methods. New cards were added to the beginning of the array and deleting a card meant removing the first card in the array. This worked well and the code was simple. However, I decided to implement what seemed like a very simple feature: display the total number of cards and the number of the current card. This little feature required a rewrite and it took a few days to figure out.`,
            lessons: `One of the lessons learned was to not underestimate seemingly simple features. But also it doesn't seem like too many people are interested in a flashcard app, at least not the people I showed it to. Regardless it scratched an itch and I just wanted to see if I could code the thing.`,
            code: `https://github.com/luiswoohoo/flashcards_app`,
            site: `https://cardstack.netlify.app/`,
        },
    },
    {
        name: 'Quizzical',
        tech: 'React',
        description: `A quiz app built with React that pulls trivia from the Open Trivia DB API. The design is from Scrimba.com, but I coded the app from scratch.`,
        src: 'Quizzical_mgqb7k',
        width: '700',
        height: '350',
        alt: 'Quiz app',
        longDescription: {
            intro: ``,
            problems: ``,
            lessons: ``,
            code: `https://github.com/luiswoohoo/quizzical`,
            site: `https://quizzicalr.netlify.app/`,
        },
    },
    {
        name: 'Movie Finder',
        tech: 'JS • Serverless Functions',
        description: `A movie app built in vanilla JS that pulls movie data from the OMDB API. A couple of serverless functions are used to hide the API key from the client. The design is from Scrimba.com, but I built the app completely from scratch.`,
        src: 'MovieFinder_figuse',
        width: '700',
        height: '350',
        alt: 'Movie finder app',
        longDescription: {
            intro: ``,
            problems: ``,
            lessons: ``,
            code: `https://github.com/luiswoohoo/movie_search_test`,
            site: `https://mov-watch.netlify.app/`,
        },
    },
    {
        name: 'Invoice Automation',
        tech: 'Google Apps Script',
        description: `I was creating invoices for a trucking company and wondered if there was a way to automate the process. That's when I discovered Google Apps Script. I was able to speed up my workflow and discovered how much I enjoy coding.`,
        src: 'GAS_kyjfhj',
        width: '700',
        height: '350',
        alt: 'Google Apps Script',
        longDescription: {
            intro: `I was creating invoices for a trucking company and wondered if there was a way to automate the process. That's when I discovered Google Apps Script. It's essentially JS with methods that tap into Google Drive. I was able to speed up my workflow and discovered how much I enjoy coding. This sparked my motivation to consider coding as a career.`,
            problems: ``,
            lessons: ``,
            code: ``,
            site: ``,
        },
    },
]

export { projectsData }
